application: a1drinweb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/img/icon.ico
  upload: static/img/icon\.ico

- url: /update
  script: dynamic.app
  login: admin

- url: /.*
  script: dynamic.app
