application: ajdweb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: ajdweb/static

- url: /favicon\.ico
  static_files: ajdweb/static/img/icon.ico
  upload: ajdweb/static/img/icon\.ico

- url: /update
  script: ajdweb.app
  login: admin

- url: /.*
  script: ajdweb.app
